config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'

  resources :teams, only: [:index]
  resources :athletes, only: [:index]

  namespace :administration, as: 'admin', path: 'administration' do
    resources :teams, path: 'nations', only: [:index, :create, :update, :destroy]
    resources :stages, path: 'etapes', only: [:index, :edit, :update]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :team, presence: true

  belongs_to :team
end

app/models/event.rb
class Event < ApplicationRecord
  enum format: [:individual, :sprint, :pursuit, :mass_start, :relay, :mixed_relay, :single_mixed_relay]
  enum gender: [:masculine, :female, :mixed]

  belongs_to :stage

  def humanize
    case format.to_sym
    when :individual
      "individuel #{humanize_gender}"
    when :sprint
      "sprint #{humanize_gender}"
    when :pursuit
      "poursuite #{humanize_gender}"
    when :mass_start
      "mass start #{humanize_gender}"
    when :relay
      "relais #{humanize_gender}"
    when :mixed_relay
      'relais mixte'
    when :single_mixed_relay
      'relai mixte simple'
    else
      raise "Format d'épreuve inconnu"
    end
  end

  def humanize_date
    "#{date.strftime('%d/%m')}"
  end

  def humanize_gender
    case gender.to_sym
    when :masculine
      "homme"
    when :female
      "femme"
    else
      ""
    end
  end
end

app/models/stage.rb
class Stage < ApplicationRecord
  has_many :events

  def humanize_date
    "#{start_date.strftime('%d/%m')} - #{end_date.strftime('%d/%m')}"
  end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, uniqueness: true
  validates :short_name, length: { is: 3 }, uniqueness: true

  has_many :athletes
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :set_admin

  def set_admin
    @admin = true
  end
  
end

app/controllers/administration/stages_controller.rb
class Administration::StagesController < AdminController

  def index
    @stages = Stage.includes(:events).all
  end

  def edit
    @stage = Stage.find(params[:id])
  end

end

app/controllers/administration/teams_controller.rb
class Administration::TeamsController < AdminController

  def index
    # @teams = Team.includes(:athletes).all.order(:name)
    @teams = Team.all.order(:name)
    @team = Team.new
  end

  def create
    team = Team.new(team_params)
    team.short_name = team.short_name.upcase
    if team.save
      flash[:notice] = "Nation enregistrée"
      redirect_to teams_path
    else
      binding.pry
    end
  end

  def update
    @team = Team.find(params[:id])
    if @team.update_attributes(team_params)
      flash[:notice] = "Mise à jour de la nation réussie"
    end
  end

  private

  def team_params
    params.require(:team).permit(:short_name, :name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController

  def index
    @athletes = Athlete.all.order(:last_name)
    
    # For create Athlete
    @athlete = Athlete.new
    @teams = Team.all
  end

  def destroy
    athlete = Athlete.find(params[:id])
    if athlete
      athlete.delete
    end
    redirect_to athletes_path
  end

  def create
    athlete = Team.new(athlete_params)
    if athlete.save
      redirect_to athletes_path
    else
      binding.pry
    end
  end

  private

  def athlete_params
    params.require(:athlete).permit(:first_name, :last_name, :team_id)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all.order(:name)
    @athletes = Athlete.all.order(:last_name)

    # For create Team
    @team = Team.new
  end

  def destroy
    team = Team.find(params[:id])
    if team
      team.delete
    end
    redirect_to teams_path
  end

  def create
    team = Team.new(team_params)
    team.short_name = team.short_name.upcase
    if team.save
      redirect_to teams_path
    else
      binding.pry
    end
  end

  private

  def team_params
    params.require(:team).permit(:short_name, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/administration/stages/index.haml
#stage-index.row
  %ul.collapsible.col.l6.offset-l3
    - @stages.each do |stage|
      %li
        .collapsible-header.stages
          %span= stage.humanize_date
          = image_tag("flag/#{stage.country.downcase}", class: 'flag') if File.exist?("#{Rails.root}/app/assets/images/flag/#{stage.country.downcase}.png")
          %span= stage.city
          = link_to root_path, class: 'flag-edit' do
            %i.material-icons edit
        .collapsible-body.events
          %ul
            - now = DateTime.now
            - stage.events.each do |event|
              %li.event
                .text
                  = event.humanize_date
                  = event.humanize.capitalize

app/views/administration/teams/index.haml
#admin-teams
  %a.add-team{ onclick: 'showAddTeam();' }
    %i.material-icons.medium add_circle_outline
  %h2 Gestion des nations
  .row
    .col.l6.offset-l3.s10.offset-s1
      %ul#collection-list.collapsible{ "data-collapsible" => "accordion" }
        - @teams.each_with_index do |team, index|
          %li
            %div{class: "bloc-header item#{index}"}
              .div-flag.unclickable{ onclick: 'return false;' }
                = image_tag("flag/#{team.short_name.downcase}", class: 'flag') if File.exist?("#{Rails.root}/app/assets/images/flag/#{team.short_name.downcase}.png")
              .nation_name.unclickable= team.name
              %span.badge
                %i.material-icons.flag-edit edit
                - if team.athletes.empty?
                  = link_to team_path(team.id), method: :delete, class: 'secondary-content', title: "Supprimer cette nation" do
                    %i.material-icons delete
                - else
                  %i.material-icons{ title: 'Suppression impossible : des athlètes sont associés à cette nation' } lock_outline
            %div{class: "collapsible-body bloc-body item#{index}"}
              = form_for team do |f|
                .input-field.col.l4.s4
                  = f.text_field(:short_name, class: 'short_name', maxlength: 3)
                  = f.label(:short_name, "Abréviation")
                .input-field.col.l8.s8
                  = f.text_field(:name)
                  = f.label(:name, "Nom")
                = f.submit('Modifier', class: 'btn')
      %ul#formAddTeam.collapsible
        %li.new-team
          #addTeamHeader.collapsible-header.active{ onclick: "return false;" }
            %i.material-icons.medium add
            Ajouter une nation
          #addTeamBody.collapsible-body{  }
            = form_for @team do |f|
              .input-field.col.l4
                = f.text_field(:short_name, class: 'short_name', maxlength: 3)
                = f.label(:short_name, "Abréviation")
              .input-field.col.l8
                = f.text_field(:name)
                = f.label(:name, "Nom")
              = f.submit('Ajouter', class: 'modal-close btn')

app/views/athletes/_modal_add_athlete.haml
#modal-addAthleteForm.modal.new-athlete.col.l3.offset-l1
  = form_for @athlete do |f|
    .modal-content
      .input-field
        = f.label(:last_name, "Nom")
        = f.text_field(:last_name)
      .input-field
        = f.label(:first_name, "Prénom")
        = f.text_field(:first_name)
    .modal-footer
      = f.submit('Ajouter', class: 'modal-close btn')

app/views/athletes/index.haml
#index-athlete.row
  .athletes.col.l6.offset-l3.s12.lists
    %ul.collection.with-header
      %li.collection-header
        %h4
          Les athlètes
        %a.waves-effect.waves-light.modal-trigger.editable.hide{ href: "#modal-addAthleteForm" }
          %i.material-icons add_circle
      - @athletes.each do |athlete|
        %li{ class: "collection-item #{'my-selection' if athlete.team.short_name == 'FRA' }", onclick: "showAthletes();" }
          .athlete_name= "#{athlete.last_name} #{athlete.first_name}"
          = link_to athlete_path(athlete.id), method: :delete, class: 'secondary-content editable hide' do
            %i.material-icons delete

= render partial: 'athletes/modal_add_athlete'

app/views/layouts/_navbar.haml
%nav
  .nav-wrapper
    - if @admin
      %ul
        %li
          = link_to 'Nations', admin_teams_path
        %li
          = link_to 'Étapes', admin_stages_path
    - else
      %ul#nav-mobile.left.hide-on-med-and-down
        %li
          %a{ href: root_path }
            %i.material-icons home
        %li
          = link_to 'Nations', teams_path
        %li
          = link_to 'Athlètes', athletes_path

      %ul#nav-mobile.right.hide-on-med-and-down
        %li
          %a{ onclick: "changeEditMode();" }
            %i.material-icons edit

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Biathlon
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/navbar'
    %main
      = yield